"""empty message

Revision ID: 39eb65e528f1
Revises: 2cbf3d863e0d
Create Date: 2022-08-22 00:39:38.251748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39eb65e528f1'
down_revision = '2cbf3d863e0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), server_default='1', nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_question_user_id'), 'user', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_question_user_id'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
