"""empty message

Revision ID: 59454eece598
Revises: 52c9dada9270
Create Date: 2022-08-30 14:56:55.986858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59454eece598'
down_revision = '52c9dada9270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer_voter', schema=None) as batch_op:
        batch_op.alter_column('answer_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer_voter', schema=None) as batch_op:
        batch_op.alter_column('answer_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
