"""empty message

Revision ID: d392fc9a29c5
Revises: b6186d4676ae
Create Date: 2022-08-15 13:02:16.571541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd392fc9a29c5'
down_revision = 'b6186d4676ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('create_date', sa.DateTime(), nullable=False))
    op.drop_column('answer', 'creaete_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('creaete_date', sa.DATETIME(), nullable=False))
    op.drop_column('answer', 'create_date')
    # ### end Alembic commands ###
